### PR TITLE
refactor: replace sharp with canvas

### PR DESCRIPTION
**Pull request by eventualbuddha**
Sharp has some memory leak problems on Linux, and canvas is just faster.

### CODE REVIEW

**Review by benadida — APPROVED** [review]
I'm a tad confused as to why some of the scores changed, but maybe because of a slightly different geometry of the whole thing, off by a pixel?

Also, note the Github action note on `src/Interpreter.ts` line 462, `columns` defined but not used.

**Comment by eventualbuddha** [comment]
Yeah, I'm unsure about the changes to the scores too. I think it's fine, but it might point to a difference in PNG or JPEG decoding?

**Comment by eventualbuddha** [comment]
Hmm, one of the score changes was in [this file](https://github.com/votingworks/hmpb-interpreter/blob/6c2a757bf98cea6d07f27411e632d7b52b3e6446/test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1.jpg), and reading that file with both canvas and sharp yields identical image data:

```ts
❯ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> s=require('sharp')
…snip…
> c=require('canvas')
…snip…
> c.loadImage('test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1.jpg').then(_=>img=_)
Promise { <pending> }
> img
[Image:2544x3300 test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1.jpg complete]
> can=c.createCanvas(img.width, img.height)
[Canvas 2544x3300]
> ctx=can.getContext('2d')
CanvasRenderingContext2D { canvas: [Canvas 2544x3300] }
> ctx.drawImage(img, 0, 0)
undefined
> cd=ctx.getImageData(0,0,img.width,img.height)
ImageData {
  data: Uint8ClampedArray(33580800) [
      0,   0,   0, 255,   0,   0,   0, 255,  17,  17,  17, 255,
      0,   0,   0, 255, 252, 252, 252, 255,   0,   0,   0, 255,
      2,   2,   2, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255,
    ... 33580700 more items
  ]
}
> sharp('test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1.jpg').raw().ensureAlpha().toBuffer({resolveWithObject:true}).then(_=>simg=_)
Uncaught ReferenceError: sharp is not defined
> s('test/fixtures/election-4e31cb17d8-ballot-style-77-precinct-oaklawn-branch-library/filled-in-p1.jpg').raw().ensureAlpha().toBuffer({resolveWithObject:true}).then(_=>simg=_)
Promise { <pending> }
> simg
{
  data: <Buffer 00 00 00 ff 00 00 00 ff 11 11 11 ff 00 00 00 ff fc fc fc ff 00 00 00 ff 02 02 02 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ... 33580750 more bytes>,
  info: {
    format: 'raw',
    width: 2544,
    height: 3300,
    channels: 4,
    premultiplied: false,
    size: 33580800
  }
}
> ch=require('crypto').createHash('sha256').update(cd.data).digest('hex')
'02c4f63c30677c601860e2c28ef812c8d3c5e21abe1ae75d623f7d8184729816'
> sh=require('crypto').createHash('sha256').update(simg.data).digest('hex')
'02c4f63c30677c601860e2c28ef812c8d3c5e21abe1ae75d623f7d8184729816'
```

**Comment by eventualbuddha** [comment]
Well, as this code isn't even used in `module-scan` to load images, I'm going to just ignore this for now.

**Pull request merged**
